export type Block =
  | { type: "h2"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] };

export interface Post {
  slug: string;
  title: string;
  description: string;
  keyword: string;
  date: string;
  readMins: number;
  body: Block[];
}

export const POSTS: Post[] = [
  {
    slug: "how-to-calculate-voltage-drop",
    title: "How to Calculate Voltage Drop (with the NEC Tables)",
    description: "The voltage drop formula explained, with worked single-phase and three-phase examples using the real NEC Chapter 9 Table 8 conductor resistances.",
    keyword: "how to calculate voltage drop",
    date: "2026-06-14",
    readMins: 6,
    body: [
      { type: "p", text: "Voltage drop is the voltage a conductor loses to its own resistance along a run. The longer the wire and the higher the current, the more you lose. Here's how to calculate it the way the NEC intends." },
      { type: "h2", text: "The formula" },
      { type: "p", text: "For a single-phase or DC circuit, Vd = 2 × I × R × L, where I is the current in amps, R is the conductor resistance in ohms per foot, and L is the one-way length. The factor of 2 accounts for the current flowing out and back. For three-phase, swap the 2 for √3 (1.732)." },
      { type: "h2", text: "Where R comes from" },
      { type: "p", text: "Use NEC Chapter 9, Table 8. It lists the DC resistance of every conductor in ohms per 1,000 feet at 75°C — for example, 12 AWG copper is 1.93 Ω/kFT and 4/0 copper is 0.0608 Ω/kFT. Divide by 1,000 to get ohms per foot." },
      { type: "h2", text: "A worked example" },
      { type: "p", text: "A 120 V circuit carrying 20 A through 12 AWG copper, 100 ft away: Vd = 2 × 20 × (1.93 ÷ 1000) × 100 = 7.72 V, or 6.4% — well over the 3% the NEC recommends. Stepping up to 8 AWG brings it under 3%. Our voltage drop calculator does this instantly and suggests the smallest compliant wire." },
    ],
  },
  {
    slug: "what-size-wire-for-50-amps",
    title: "What Size Wire Do You Need for 50 Amps?",
    description: "The right copper and aluminum wire size for a 50 amp circuit, why terminal temperature ratings matter, and when to upsize for voltage drop.",
    keyword: "what size wire for 50 amps",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "A 50 amp circuit — common for ranges, EV chargers and sub-panels — needs 6 AWG copper or 4 AWG aluminum on 60°C-rated terminals, which is the NEC default for circuits 100 A and under. On 75°C-rated terminals you may use 8 AWG copper or 6 AWG aluminum. Here's why the terminal rating decides it." },
      { type: "h2", text: "It comes down to the terminal column" },
      { type: "p", text: "NEC 110.14(C)(1) says circuits of 100 A or less are sized from the 60°C column unless the terminals are listed for 75°C. In the 60°C column, 8 AWG copper is only 40 A — short of 50 — so you step up to 6 AWG copper (55 A). If your breaker and lugs are rated 75°C (most modern ones are), 8 AWG copper (50 A) is permitted." },
      { type: "h2", text: "Aluminum runs one size larger" },
      { type: "p", text: "Aluminum 6 AWG is only 40 A at 60°C, so a 50 A circuit takes 4 AWG aluminum on 60°C terminals (or 6 AWG aluminum on 75°C). That's the usual one-to-two-size penalty for aluminum." },
      { type: "h2", text: "When to upsize" },
      { type: "p", text: "On long runs, voltage drop can force a larger wire than ampacity alone. A 50 A load 150 ft out will often need 4 AWG copper to stay under 3%. Run your exact numbers through the wire size and voltage drop calculators." },
    ],
  },
  {
    slug: "copper-vs-aluminum-wire",
    title: "Copper vs Aluminum Wire: Sizing and Trade-offs",
    description: "How aluminum and copper conductors compare on ampacity, resistance, voltage drop and cost — and how many sizes up aluminum needs to go.",
    keyword: "copper vs aluminum wire",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "Aluminum conductors are cheaper and lighter than copper, which is why most utility service and large feeders use them. The trade-off is lower ampacity and higher resistance for the same size." },
      { type: "h2", text: "The size penalty" },
      { type: "ul", items: [
        "100 A: 3 AWG copper vs 1 AWG aluminum.",
        "200 A: 4/0 copper vs 250 kcmil aluminum.",
        "As a rule of thumb, aluminum runs about two sizes larger than copper for the same job.",
      ] },
      { type: "h2", text: "Resistance and voltage drop" },
      { type: "p", text: "Aluminum's resistance is roughly 60% higher than copper (12 AWG: 3.18 vs 1.93 Ω/kFT), so it drops more voltage over the same distance — another reason to upsize it." },
      { type: "h2", text: "Terminations matter" },
      { type: "p", text: "Aluminum requires terminals rated CO/ALR or AL/CU and an anti-oxidant compound on larger conductors. Done correctly it's perfectly safe and code-compliant; done poorly it's a fire risk." },
    ],
  },
  {
    slug: "12-volt-wire-size-guide",
    title: "12 Volt Wire Size Guide (Solar, RV and Marine)",
    description: "Why low-voltage DC systems need much larger wire, how to size 12V/24V/48V conductors for voltage drop, and a worked solar example.",
    keyword: "12 volt wire size",
    date: "2026-06-14",
    readMins: 6,
    body: [
      { type: "p", text: "On a 12-volt system, voltage drop is the whole game. The same drop that's trivial at 240 V is catastrophic at 12 V, because it's a far bigger percentage of your supply. That's why solar, RV and marine wiring is so chunky." },
      { type: "h2", text: "Why low voltage needs big wire" },
      { type: "p", text: "A 3% drop at 120 V is 3.6 V; at 12 V it's only 0.36 V. To deliver real power you push high current, and high current over any resistance loses volts fast. Low-voltage DC systems are usually designed to a tighter 2–3% target." },
      { type: "h2", text: "A solar example" },
      { type: "p", text: "A 12 V circuit carrying 30 A through 10 AWG copper just 20 ft away drops about 1.45 V — over 12%. You'd need 4 AWG or larger to keep it sensible. Always size DC runs by voltage drop, not just ampacity." },
      { type: "h2", text: "Use the DC mode" },
      { type: "p", text: "Set the voltage drop calculator to DC and your system voltage (12, 24 or 48 V). It uses the same Table 8 resistances and shows exactly how much you're losing." },
    ],
  },
  {
    slug: "how-many-wires-in-conduit",
    title: "How Many Wires Can You Put in a Conduit?",
    description: "The NEC conduit fill rules explained — 53/31/40% limits, how to count conductors, and a quick reference for 12 AWG THHN in EMT.",
    keyword: "how many wires in conduit",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "The number of wires a conduit can hold is set by the NEC's fill limits in Chapter 9, Table 1 — and it's less than most people expect, because the rule is about pulling tension and heat, not just whether the wires physically fit." },
      { type: "h2", text: "The fill limits" },
      { type: "ul", items: [
        "1 conductor: 53% of the conduit's internal area.",
        "2 conductors: 31%.",
        "3 or more conductors: 40%.",
      ] },
      { type: "h2", text: "A quick reference" },
      { type: "p", text: "For 12 AWG THHN, a 1/2\" EMT holds 9, a 3/4\" holds 16, and a 1\" holds 26. Every conductor counts — including the equipment ground and the neutral." },
      { type: "h2", text: "Mixed sizes" },
      { type: "p", text: "When conductors differ in size, add up each one's area from Table 5 and compare the total to 40% of the conduit area. The conduit fill calculator does this for EMT, PVC and rigid in one step." },
    ],
  },
  {
    slug: "what-size-wire-for-100-amp-sub-panel",
    title: "What Size Wire for a 100 Amp Sub-Panel?",
    description: "The conductor and ground sizes for a 100 amp sub-panel feeder in copper or aluminum, plus the four-wire rule for detached buildings.",
    keyword: "wire size for 100 amp sub panel",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "A 100 amp sub-panel feeder is typically 3 AWG copper or 1 AWG aluminum on 75°C terminals, with a separate equipment grounding conductor. Here's the full picture." },
      { type: "h2", text: "Feeder conductors" },
      { type: "p", text: "NEC Table 310.16 puts 3 AWG copper at 100 A and 1 AWG aluminum at 100 A in the 75°C column. Many electricians use 2 AWG copper or 1/0 aluminum for a little headroom." },
      { type: "h2", text: "Don't forget the ground" },
      { type: "p", text: "A sub-panel feeder needs an equipment grounding conductor sized from Table 250.122 — for a 100 A circuit that's 8 AWG copper. The neutral and ground must be kept separate (isolated) in a sub-panel." },
      { type: "h2", text: "Long runs" },
      { type: "p", text: "Detached garages and barns are often far from the house, so check voltage drop. A 100 A feeder 120 ft out frequently needs upsizing. Use the wire size and voltage drop calculators together." },
    ],
  },
  {
    slug: "what-size-wire-for-200-amp-service",
    title: "What Size Wire for a 200 Amp Service?",
    description: "The service-entrance conductor size for a 200 amp residential service in copper and aluminum, and why 4/0 aluminum is the standard.",
    keyword: "wire size for 200 amp service",
    date: "2026-06-14",
    readMins: 5,
    body: [
      { type: "p", text: "A 200 amp residential service uses 2/0 copper or 4/0 aluminum service-entrance conductors. The aluminum option is by far the most common because of cost." },
      { type: "h2", text: "The service conductor rule" },
      { type: "p", text: "Dwelling services get a small break: NEC 310.12 lets you size 200 A service conductors at 4/0 aluminum or 2/0 copper, slightly smaller than the general Table 310.16 values, because of how residential loads diversify." },
      { type: "h2", text: "Grounding electrode and ground" },
      { type: "p", text: "The grounding electrode conductor for a 200 A service is typically 4 AWG copper to ground rods or 250.66-sized to a water pipe. Don't confuse it with the feeder equipment ground." },
      { type: "h2", text: "Sizing your actual load" },
      { type: "p", text: "Before assuming 200 A, run the Article 220 load. Many homes calculate well under 200 A; an EV charger or heat pump can push them over. Use the dwelling load calculator to check." },
    ],
  },
  {
    slug: "wire-ampacity-and-derating-explained",
    title: "Wire Ampacity and Derating, Explained",
    description: "What ampacity means, how ambient temperature and conductor bundling reduce it, and how to apply the NEC correction and adjustment factors.",
    keyword: "wire ampacity derating",
    date: "2026-06-14",
    readMins: 6,
    body: [
      { type: "p", text: "Ampacity is the current a conductor can carry continuously without exceeding its temperature rating. The table value is a starting point — real installations almost always reduce it." },
      { type: "h2", text: "Ambient temperature correction" },
      { type: "p", text: "Table 310.16 assumes a 30°C (86°F) ambient. In a hot attic at 50°C, a 75°C conductor keeps only 75% of its rating (Table 310.15(B)(1)). Rooftop conduit in the sun can be hotter still." },
      { type: "h2", text: "Conductor bundling" },
      { type: "p", text: "When more than three current-carrying conductors share a raceway, they can't shed heat as easily, so ampacity is adjusted: 4–6 conductors to 80%, 7–9 to 70%, 10–20 to 50% (Table 310.15(C)(1))." },
      { type: "h2", text: "Putting it together" },
      { type: "p", text: "Multiply the base ampacity by both factors. A 6 AWG copper conductor (75 A at 90°C) in a hot, crowded raceway can fall below 50 A. The wire size calculator applies both factors automatically." },
    ],
  },
  {
    slug: "voltage-drop-3-percent-rule",
    title: "The 3% Voltage Drop Rule: What It Really Means",
    description: "Where the 3% and 5% voltage drop figures come from in the NEC, whether they're mandatory, and how to design to them.",
    keyword: "voltage drop 3 percent rule",
    date: "2026-06-14",
    readMins: 4,
    body: [
      { type: "p", text: "You'll hear that voltage drop must stay under 3%. The truth is more nuanced — and worth understanding before you upsize every run." },
      { type: "h2", text: "Where the numbers come from" },
      { type: "p", text: "The NEC suggests a maximum 3% drop on a branch circuit and 5% total for feeder plus branch, in Informational Notes to 210.19(A) and 215.2(A). Informational Notes are guidance, not enforceable rules — but they're widely treated as the design standard." },
      { type: "h2", text: "Why it matters" },
      { type: "ul", items: [
        "Motors lose torque and run hotter on low voltage.",
        "LED drivers and electronics can misbehave or fail early.",
        "Resistance heating and lighting simply underperform.",
      ] },
      { type: "h2", text: "Designing to it" },
      { type: "p", text: "Pick a target, enter your run, and let the calculator find the smallest conductor that meets it. On long runs that wire is often a size or two above what ampacity alone would require." },
    ],
  },
  {
    slug: "what-size-wire-for-30-amps",
    title: "What Size Wire for 30 Amps?",
    description: "The correct wire for a 30 amp circuit (dryers, water heaters, RV outlets) in copper and aluminum, and the 10 AWG rule.",
    keyword: "what size wire for 30 amps",
    date: "2026-06-14",
    readMins: 4,
    body: [
      { type: "p", text: "A 30 amp circuit — dryers, electric water heaters, RV outlets — calls for 10 AWG copper or 8 AWG aluminum. It's one of the most common circuits in a home." },
      { type: "h2", text: "The 10 AWG rule" },
      { type: "p", text: "10 AWG copper is rated 35 A at 75°C, but the 240.4(D) small-conductor rule caps it at a 30 A breaker — which is exactly what a 30 A circuit needs. Aluminum 10 AWG is only 30 A, so 8 AWG aluminum is the safer pick." },
      { type: "h2", text: "Don't undersize on a long run" },
      { type: "p", text: "A 30 A load 100 ft out on 10 AWG copper drops about 3%, right at the limit. Beyond that, step up to 8 AWG. The voltage drop calculator shows the exact figure for your distance." },
      { type: "h2", text: "Match the breaker" },
      { type: "p", text: "A 30 A circuit takes a 30 A breaker — never put 10 AWG on a 40 A breaker. The wire size calculator returns the correct standard breaker and ground for any load." },
    ],
  },
  {
    slug: "how-to-convert-watts-to-amps",
    title: "How to Convert Watts to Amps",
    description: "The watts-to-amps formula for single-phase, three-phase and DC, why voltage and power factor matter, and worked examples.",
    keyword: "watts to amps",
    date: "2026-06-19",
    readMins: 5,
    body: [
      { type: "p", text: "Watts measure how much power a device actually uses; amps measure the current flowing to it. You can't convert one to the other without knowing the voltage — and for AC, the power factor." },
      { type: "h2", text: "The formula" },
      { type: "ul", items: [
        "Single-phase: amps = watts ÷ (volts × power factor)",
        "Three-phase: amps = watts ÷ (√3 × volts × power factor)",
        "DC: amps = watts ÷ volts",
      ] },
      { type: "h2", text: "A worked example" },
      { type: "p", text: "A 1,500 W heater on a 120 V circuit draws 1500 ÷ 120 = 12.5 A (heaters are resistive, so power factor is 1.0). That's why a 1,500 W heater is right at the edge of a 15 A circuit." },
      { type: "h2", text: "Why power factor matters" },
      { type: "p", text: "Motors and many electronic loads have a power factor below 1.0, meaning they draw more current than their wattage alone suggests. A 1,000 W motor at 0.8 power factor on 120 V draws 1000 ÷ (120 × 0.8) = 10.4 A, not 8.3 A. The watts-to-amps calculator handles all three system types and power factor for you." },
    ],
  },
  {
    slug: "ohms-law-explained",
    title: "Ohm's Law Explained (with Examples)",
    description: "What Ohm's law is, the V = I × R relationship, how power fits in, and how to solve any value from the other two.",
    keyword: "ohms law",
    date: "2026-06-19",
    readMins: 4,
    body: [
      { type: "p", text: "Ohm's law is the single most useful relationship in electrical work. It says voltage equals current times resistance: V = I × R. Rearrange it and you can find any one of the three from the other two." },
      { type: "h2", text: "The three forms" },
      { type: "ul", items: [
        "V = I × R  (find voltage)",
        "I = V ÷ R  (find current)",
        "R = V ÷ I  (find resistance)",
      ] },
      { type: "h2", text: "Adding power" },
      { type: "p", text: "Power (watts) ties in through P = V × I. Combined with Ohm's law that gives P = I²R and P = V²/R, so from any two of voltage, current, resistance and power you can find the other two." },
      { type: "h2", text: "Example" },
      { type: "p", text: "A device on 120 V drawing 0.5 A has a resistance of 120 ÷ 0.5 = 240 Ω and consumes 120 × 0.5 = 60 W. Enter any two values into the Ohm's law calculator and it solves the rest instantly." },
    ],
  },
  {
    slug: "how-to-convert-kw-to-amps",
    title: "How to Convert kW to Amps",
    description: "Convert kilowatts to amps for single-phase, three-phase and DC systems, with the formulas and a generator-sizing example.",
    keyword: "kw to amps",
    date: "2026-06-19",
    readMins: 4,
    body: [
      { type: "p", text: "Kilowatts (kW) are just 1,000 watts. To turn a kW rating into the current it draws, you need the voltage and — for AC — the power factor." },
      { type: "h2", text: "The formula" },
      { type: "ul", items: [
        "Single-phase: amps = (kW × 1000) ÷ (volts × pf)",
        "Three-phase: amps = (kW × 1000) ÷ (√3 × volts × pf)",
        "DC: amps = (kW × 1000) ÷ volts",
      ] },
      { type: "h2", text: "Generator example" },
      { type: "p", text: "A 22 kW standby generator at 240 V single-phase delivers about 22000 ÷ 240 = 91.7 A — which is why it typically lands on a 100 A transfer switch. For a three-phase 22 kW load at 208 V and 0.8 pf, the current is 22000 ÷ (√3 × 208 × 0.8) ≈ 76 A." },
      { type: "h2", text: "Do it instantly" },
      { type: "p", text: "Set the power calculator to kW (via watts), choose your phase and voltage, and read off the amps — then size the conductor with the wire size calculator." },
    ],
  },
];

export function getPost(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug);
}

const WEEK2_POSTS: Post[] = [
  {
    slug: "gfci-outlet-requirements-nec",
    title: "Where Are GFCI Outlets Required by the NEC?",
    description: "The NEC requires GFCI protection in bathrooms, kitchens, garages, outdoors and anywhere near water. Here's the full room-by-room list and the rules behind it.",
    keyword: "gfci requirements",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Ground fault circuit interrupter (GFCI) protection is one of the most life-safety-critical requirements in the NEC. Since the 1970s, the list of required GFCI locations has grown with each code cycle. Here's where you need it in a residential installation under the 2023 NEC." },
      { type: "h2", text: "Bathrooms (NEC 210.8(A)(1))" },
      { type: "p", text: "All 125V, 15 and 20 amp receptacles in bathrooms require GFCI protection. This applies to every bathroom, including half baths and powder rooms. A single GFCI receptacle can protect downstream receptacles on the same circuit via its load-side terminals." },
      { type: "h2", text: "Kitchens (NEC 210.8(A)(6))" },
      { type: "p", text: "All 125V, 15 and 20 amp receptacles that serve countertop surfaces require GFCI protection. This includes any outlet within 6 feet of a sink (added in 2020 NEC to cover the entire countertop area)." },
      { type: "h2", text: "Garages and accessory buildings (NEC 210.8(A)(2))" },
      { type: "p", text: "All 125V, 15 and 20 amp receptacles in garages and grade-level accessory buildings require GFCI protection. This includes attached and detached garages, carports and similar structures." },
      { type: "h2", text: "Outdoors (NEC 210.8(A)(3))" },
      { type: "p", text: "All 125V, 15 and 20 amp outdoor receptacles require GFCI protection. This covers any outlet accessible from the exterior of the building — including deck outlets, porch outlets and outlets under eaves." },
      { type: "h2", text: "Crawl spaces and unfinished basements (NEC 210.8(A)(4) and (5))" },
      { type: "p", text: "Crawl spaces and unfinished basements require GFCI protection on all 125V, 15 and 20 amp receptacles. Finished portions of a basement that are conditioned living space are not required to be GFCI-protected under (5), though individual jurisdictions may require it." },
      { type: "h2", text: "Near sinks in other rooms (NEC 210.8(A)(7))" },
      { type: "p", text: "Any receptacle within 6 feet of a sink in a room other than a bathroom or kitchen — laundry rooms, utility rooms, wet bars — requires GFCI protection under the 2020 NEC's expanded scope." },
    ],
  },
  {
    slug: "electrical-conduit-types-guide",
    title: "Electrical Conduit Types: EMT, PVC and Rigid",
    description: "EMT, rigid metal, IMC, PVC and flexible conduit each have different code applications. Here's which conduit to use where and how they compare on cost and install.",
    keyword: "conduit types",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Conduit is a raceway for electrical conductors — it protects wires from physical damage, lets you pull additional circuits later, and is often required by the NEC in locations where cable is not permitted. Different types suit different environments and installation needs." },
      { type: "h2", text: "EMT (Electrical Metallic Tubing)" },
      { type: "p", text: "EMT is thin-wall steel conduit, the most common type in commercial and light industrial work. It is lightweight, easy to bend with a hand bender, and accepts standard compression fittings. EMT is listed for exposed interior locations and in concrete; it is not suitable for direct burial or where severe physical damage is likely. Most commercial office and retail wiring uses EMT." },
      { type: "h2", text: "Rigid Metal Conduit (RMC) and IMC" },
      { type: "p", text: "RMC is heavy-wall threaded steel conduit — the most durable option, approved for all locations including direct burial, concrete encasement and outdoor exposed applications. It is heavy and requires a pipe threader to make joints. Intermediate Metal Conduit (IMC) is thinner-walled than RMC but heavier than EMT, used in similar applications at lower weight." },
      { type: "h2", text: "PVC Conduit (Schedule 40 and Schedule 80)" },
      { type: "p", text: "PVC conduit is the standard for underground direct burial and wet or corrosive environments. Schedule 40 is used in most residential and light commercial underground runs; Schedule 80 is thicker-walled and required where subject to physical damage above grade. PVC cannot be bent with a heat gun indoors without ventilation and requires solvent-weld fittings." },
      { type: "h2", text: "Flexible Metal Conduit (FMC) and LFMC" },
      { type: "p", text: "FMC (Greenfield) is an interlocked armored spiral — it bends without bending tools. It is used for final connections to equipment where vibration is present (HVAC units, motors) and where rigid conduit cannot be run. Liquid-tight Flexible Metal Conduit (LFMC) adds a plastic jacket for wet locations and outdoor equipment connections." },
      { type: "ul", items: [
        "EMT: indoor exposed and in concrete, bends with hand bender, most common.",
        "RMC/IMC: all locations including outdoor, direct burial, severe physical damage.",
        "PVC Sched 40/80: underground, corrosive environments, wet locations.",
        "FMC/LFMC: final connections to vibrating equipment, HVAC, motors.",
      ] },
    ],
  },
  {
    slug: "ev-charger-wiring-requirements",
    title: "EV Charger Wiring: Circuit Size and NEC Rules",
    description: "A Level 2 home EV charger needs a 240V dedicated circuit. Here's how to size the breaker and wire, what the NEC 625 requirements are, and when to upgrade your panel.",
    keyword: "ev charger wiring",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Installing a Level 2 home EV charger (EVSE — Electric Vehicle Supply Equipment) is one of the most common electrical upgrades homeowners are adding. Here's what is involved from a code and wiring standpoint." },
      { type: "h2", text: "Level 1 vs Level 2 charging" },
      { type: "p", text: "Level 1 charging uses a 120V outlet (15 or 20 amp) and adds about 3–5 miles of range per hour. Level 2 uses 240V and adds 20–30 miles per hour depending on the charger output. For daily drivers, Level 2 is strongly preferred. A Level 2 EVSE typically requires a 40 or 50 amp, 240V dedicated circuit." },
      { type: "h2", text: "Sizing the circuit" },
      { type: "p", text: "NEC Article 625 requires EVSE circuits to be rated at 125% of the EVSE's continuous current draw. A 32 amp EVSE (the most common Level 2 output) needs a circuit rated at 32 × 1.25 = 40 amps minimum. Most installers use a 50 amp circuit (6 AWG copper) to allow future upgrade to a 40 amp EVSE without rewiring." },
      { type: "h2", text: "Wire size for a 40-amp EV circuit" },
      { type: "p", text: "A 40-amp dedicated circuit uses 8 AWG copper (or 6 AWG aluminum) on 75°C-rated terminals. A 50-amp circuit uses 6 AWG copper (or 4 AWG aluminum). Use two hots, a neutral (for the EVSE's standby electronics) and a ground — standard 6/3 or 8/3 NM cable for indoor runs, or THW/THWN conductors in conduit for exposed or outdoor runs." },
      { type: "h2", text: "NEC 625 requirements" },
      { type: "ul", items: [
        "The circuit must be a dedicated branch circuit — no shared outlets.",
        "The EVSE must be listed (UL 2594 or equivalent).",
        "Outdoor EVSE must be in a NEMA 3R enclosure or listed for outdoor use.",
        "The outlet or hardwired connection must be within cord reach of the vehicle's charging port.",
        "A disconnect means within sight of a hardwired EVSE is required in some jurisdictions.",
      ] },
      { type: "h2", text: "Panel upgrade considerations" },
      { type: "p", text: "A 40–50 amp EV circuit adds a significant continuous load. If your panel is already loaded near capacity, you may need a sub-panel, panel upgrade, or load management system. A qualified electrician can perform a load calculation (NEC Article 220) to determine available capacity." },
    ],
  },
  {
    slug: "circuit-breaker-keeps-tripping",
    title: "Why a Circuit Breaker Keeps Tripping (and What to Do)",
    description: "A tripping breaker means overload, short circuit or ground fault. Here's how to diagnose which of the three is causing it and what each repair requires.",
    keyword: "breaker keeps tripping",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "A circuit breaker that trips repeatedly is telling you something is wrong — either on the circuit itself, in the connected devices, or (rarely) in the breaker itself. Here's how to narrow down the cause." },
      { type: "h2", text: "The three causes of tripping" },
      { type: "ul", items: [
        "Overload: too many devices drawing more current than the circuit is rated for.",
        "Short circuit: a hot conductor touches a neutral or ground, creating a low-resistance path that pulls extreme current.",
        "Ground fault: a hot conductor touches a grounded metal surface or a person, creating a leakage path to ground.",
      ] },
      { type: "h2", text: "Diagnosing an overload" },
      { type: "p", text: "An overload breaker trips when the circuit is loaded — typically after devices have been running for a few minutes. If the breaker resets immediately and trips again only when devices are on, you have an overload. Add up the wattage of all devices on the circuit and divide by 120 V (or 240 V) to find the current draw. A 15-amp circuit is rated for 12 amps continuous (80% of 15 A). Shift loads to other circuits or add a dedicated circuit." },
      { type: "h2", text: "Diagnosing a short circuit" },
      { type: "p", text: "A short circuit trips the breaker immediately when you flip it back on, often with a popping sound. Turn off every device and unplug everything on the circuit. If the breaker still trips immediately with no load, the fault is in the wiring or a device left plugged in. Plug devices in one at a time to find the culprit — a device with an internal short will trip the breaker when plugged in." },
      { type: "h2", text: "Diagnosing a ground fault" },
      { type: "p", text: "A ground fault behaves like a short — the breaker trips hard. A GFCI outlet in the same area will also trip. Ground faults commonly happen in outdoor outlets, bathroom outlets and any outlet where water is nearby. Check for moisture in outlet boxes and damaged cord insulation on devices in that area." },
      { type: "h2", text: "When to replace the breaker" },
      { type: "p", text: "Breakers are electromechanical devices that wear over time. If a breaker trips at loads well below its rating with no signs of overload, short or ground fault — and the circuit checks out fine — the breaker may be failing. Breaker replacement is inexpensive ($5–$30) and within DIY scope if you are comfortable working in the panel. Always turn off the main breaker before touching branch breakers." },
    ],
  },
  {
    slug: "wire-size-for-electric-dryer",
    title: "Wire Size for a 240V Electric Dryer",
    description: "Most electric dryers require a 30-amp, 240V dedicated circuit. Here's the right wire size, what the NEC says about 3-wire vs 4-wire dryer connections.",
    keyword: "wire size for dryer",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "An electric dryer typically draws 24–28 amps continuously during the heating cycle. The NEC requires a 30-amp dedicated branch circuit for most residential dryers — though high-performance models may call for 40 amps. Here's how to wire it correctly." },
      { type: "h2", text: "Wire size for a 30-amp dryer circuit" },
      { type: "p", text: "A 30-amp, 240V dryer circuit requires 10 AWG copper wire (or 8 AWG aluminum). Use 10/3 NM-B cable for new wiring (two hots + neutral + ground in one jacket). The outlet is a NEMA 14-30R; the breaker is a 30-amp double-pole." },
      { type: "h2", text: "3-wire vs 4-wire dryer connections" },
      { type: "p", text: "Old dryer circuits used a 3-wire connection (two hots + neutral, no separate ground — the dryer's metal frame was bonded to the neutral). The NEC eliminated the 3-wire dryer outlet for new construction starting in 1996. All new dryer circuits must use 4-wire (two hots + neutral + separate ground) with a NEMA 14-30 outlet. If you have an old 3-wire outlet and a new dryer, you can either rewire the outlet to 4-wire or modify the dryer's internal bonding strap as permitted by the dryer manufacturer's instructions." },
      { type: "h2", text: "High-capacity dryers: check the nameplate" },
      { type: "p", text: "Some large-capacity electric dryers, combination washer-dryer units or steam dryers draw more than 24 amps and may require a 40-amp circuit. Always check the dryer's nameplate — it states the required circuit amperage. NEC 220.54 also specifies the dryer load to use for panel load calculations (5 kW minimum or the nameplate kW, whichever is greater)." },
    ],
  },
  {
    slug: "how-to-size-a-circuit-breaker",
    title: "How to Size a Circuit Breaker for Any Load",
    description: "Breaker size equals load current times 1.25 for continuous loads. Here's the NEC 210.20 rule with worked examples for outlets, appliances and motor circuits.",
    keyword: "circuit breaker sizing",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Sizing a circuit breaker comes down to one NEC rule: the breaker must be rated for at least 125% of the continuous load on the circuit (NEC 210.20(A)). Here's how to apply it and what the practical limits are." },
      { type: "h2", text: "The 125% rule for continuous loads" },
      { type: "p", text: "A continuous load is one that remains energized for 3 hours or more. Most circuit loads — lights, appliances, motors — are treated as continuous for sizing purposes. NEC 210.20(A): the circuit breaker must be rated at 125% of the continuous load, plus 100% of any non-continuous load on the same circuit." },
      { type: "h2", text: "Worked examples" },
      { type: "ul", items: [
        "20-amp outlet circuit: the receptacles can supply up to 80% of the breaker rating = 16 A continuous. A 20-amp breaker handles up to 16 amps of continuous load.",
        "32-amp EV charger: 32 × 1.25 = 40 amps minimum breaker. Use a 40-amp breaker.",
        "24-amp dryer: 24 × 1.25 = 30 amps. The standard dryer breaker is a 30-amp double-pole.",
        "5-hp motor at 240V (20.7 FLA from NEC Table 430.248): motor circuit breaker max = 20.7 × 2.5 = 51.75 A, use a 50-amp breaker (NEC 430.52).",
      ] },
      { type: "h2", text: "Breaker size vs wire size" },
      { type: "p", text: "The breaker must protect the wire, not just match the load. You cannot put a 40-amp breaker on 12 AWG wire (which is rated 20 amps). The breaker must be equal to or smaller than the ampacity of the smallest conductor it protects. Size the wire for the load, then size the breaker to protect the wire." },
    ],
  },
  {
    slug: "afci-breaker-requirements-nec",
    title: "Where Are AFCI Breakers Required by the NEC?",
    description: "The NEC now requires AFCI protection in nearly every room of a home. Here's the 2023 NEC room-by-room list and why arc-fault protection is required where it is.",
    keyword: "afci breaker requirements",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Arc Fault Circuit Interrupter (AFCI) breakers detect the electrical signature of arcing — the kind of sparking that happens inside a wall when a wire is pinched, chewed or worn. Because arcing is a leading cause of home electrical fires, the NEC has steadily expanded AFCI requirements since 1999." },
      { type: "h2", text: "Required locations under the 2023 NEC" },
      { type: "p", text: "NEC 210.12(A) requires AFCI protection for all 120V, 15 and 20-amp branch circuits supplying outlets or devices in: dwelling unit bedrooms, family rooms, dining rooms, living rooms, parlors, libraries, dens, sunrooms, recreation rooms, closets, hallways, laundry areas, and similar rooms." },
      { type: "h2", text: "What that covers in practice" },
      { type: "p", text: "In a new residential installation under the 2023 NEC, virtually every 15 or 20-amp 120V circuit in the house requires AFCI protection. The main exceptions are bathroom circuits, garage circuits, HVAC circuits and kitchen small-appliance circuits — though some of these require GFCI instead." },
      { type: "h2", text: "AFCI breaker vs AFCI outlet" },
      { type: "p", text: "The most common way to provide AFCI protection is with a combination AFCI breaker at the panel. These detect both parallel arcs (wire to wire) and series arcs (within a wire). For existing wiring where a panel breaker change is impractical, an AFCI outlet device (a receptacle with built-in AFCI electronics) can protect the outlet at that location and any devices plugged into it — but it does not protect the wiring back to the panel." },
      { type: "h2", text: "Nuisance tripping" },
      { type: "p", text: "AFCI breakers sometimes trip on non-arc loads — dimmer switches, older motors, and some HVAC equipment can produce electrical signatures that the breaker misinterprets as an arc. If you experience nuisance tripping, confirm the circuit is correctly installed, then try a breaker from a different manufacturer, which may have different detection thresholds." },
    ],
  },
  {
    slug: "generator-transfer-switch-guide",
    title: "Generator Transfer Switch: Types and Sizing",
    description: "A transfer switch disconnects utility power before connecting a generator, preventing backfeed. Here's how to choose between manual, automatic and interlock types.",
    keyword: "transfer switch installation",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "Connecting a generator directly to your home panel without a transfer switch is illegal and dangerous — it can backfeed the utility grid and electrocute a lineman working on downed lines outside. A transfer switch is the required code-compliant solution." },
      { type: "h2", text: "How transfer switches work" },
      { type: "p", text: "A transfer switch mechanically or electrically prevents both utility and generator power from being connected to the same circuit at the same time. NEC Article 702 (optional standby systems) and 702.5 requires that the transfer switch prevent this interconnection — it is not optional." },
      { type: "h2", text: "Manual transfer switch" },
      { type: "p", text: "A manual transfer switch is a separate sub-panel with a double-throw switch. When the power goes out, you start the generator, then flip the switch to generator power. It powers only the selected circuits (typically 6–10 critical circuits). Typical cost: $200–$400 for the panel, plus electrician labor." },
      { type: "h2", text: "Automatic transfer switch (ATS)" },
      { type: "p", text: "An ATS senses utility power loss and starts the generator automatically, then transfers the load. When utility power returns, it transfers back and shuts the generator off. Required with a standby generator. Typical cost for a whole-home ATS: $600–$2000 plus installation." },
      { type: "h2", text: "Interlock kit" },
      { type: "p", text: "An interlock kit is a mechanical device that installs on your existing panel and prevents the main breaker and the generator input breaker from being on simultaneously. It is the lowest-cost option ($75–$200) and provides whole-panel generator access, but requires you to manually limit your loads to stay within the generator's capacity. It must be listed for your specific panel model." },
      { type: "h2", text: "Sizing the transfer switch" },
      { type: "p", text: "Size the transfer switch to match or exceed your generator's output capacity and the loads it will supply. A 10 kW generator at 240V produces about 42 amps; use a 50-amp transfer switch. For a whole-home ATS, match the switch amperage to your panel main (100, 150 or 200 amps)." },
    ],
  },
  {
    slug: "wire-size-for-electric-water-heater",
    title: "Wire Size for an Electric Water Heater",
    description: "Most 240V electric water heaters need a 30-amp circuit with 10 AWG wire. Here's the NEC 422.11 rule, sizing for 4500-watt and larger elements, and safety requirements.",
    keyword: "wire size for water heater",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "Electric water heaters are a fixed appliance with a continuous load — they heat for extended periods throughout the day. The NEC has specific rules for their circuits under Article 422 (appliances) and 210.23." },
      { type: "h2", text: "Standard 4500-watt element: 30-amp circuit" },
      { type: "p", text: "Most residential electric water heaters have 4500-watt heating elements at 240V. Current draw: 4500 W ÷ 240 V = 18.75 amps. At 125% (continuous load): 18.75 × 1.25 = 23.4 amps. A 30-amp double-pole breaker and 10 AWG copper wire is the standard installation. This leaves capacity for both elements if the thermostat ever runs them simultaneously." },
      { type: "h2", text: "Larger elements: 5500 watts" },
      { type: "p", text: "High-capacity and commercial-grade water heaters use 5500-watt elements at 240V. Current: 5500 ÷ 240 = 22.9 amps. At 125%: 28.6 amps — still fits a 30-amp breaker with 10 AWG wire. However, if the heater is listed for a specific overcurrent device size on its nameplate, use that rating per NEC 422.11." },
      { type: "h2", text: "Disconnect requirement" },
      { type: "p", text: "NEC 422.31(B) requires a disconnect within sight of the water heater, or the branch circuit breaker in the panel may serve as the disconnect if accessible and lockable. Most electricians install a dedicated disconnect switch at the water heater as a matter of practice." },
      { type: "h2", text: "T&P relief valve and bonding" },
      { type: "p", text: "The Temperature and Pressure relief valve is a plumbing requirement, not NEC — but the water heater tank and piping must be bonded to the electrical system ground per NEC 250.104(A). Confirm that metal cold and hot water piping within 5 feet of the panel is bonded to the grounding system." },
    ],
  },
  {
    slug: "electrical-panel-upgrade-when-why",
    title: "When and Why to Upgrade Your Electrical Panel",
    description: "A 100-amp panel may be too small for modern homes with EV chargers and heat pumps. Here's when an upgrade is necessary, what it involves and what it costs.",
    keyword: "new electrical panel",
    date: "2026-06-20",
    readMins: 6,
    body: [
      { type: "p", text: "The electrical panel — service entrance, main breaker and distribution panel — determines how much electricity your home can draw at once and how many circuits you can run. Older homes with 100-amp or 60-amp service are increasingly limiting in a world of EV chargers, heat pumps and whole-home air conditioning." },
      { type: "h2", text: "Signs you may need an upgrade" },
      { type: "ul", items: [
        "The panel is full and you can't add circuits without a sub-panel or upgrade.",
        "Breakers trip frequently under normal loads.",
        "You want to add an EV charger, heat pump or induction range.",
        "You have a Federal Pacific Stab-Lok or Zinsco panel (known safety issues).",
        "You have a 60-amp or 100-amp service and live in a home over 2000 square feet.",
      ] },
      { type: "h2", text: "100 amp vs 200 amp service" },
      { type: "p", text: "A 100-amp service was the standard for homes built through the 1970s. It supports typical lighting, appliances and HVAC, but leaves little room for an EV charger (40–50 amp draw) or other high-draw additions. Most new homes are built with 200-amp service. Upgrading to 200 amps from 100 amps typically costs $1,500–$4,000, depending on whether the utility must also upgrade the service drop." },
      { type: "h2", text: "What the upgrade involves" },
      { type: "p", text: "A panel upgrade requires: (1) pulling a permit, (2) coordinating with the utility to temporarily disconnect the service, (3) replacing the meter base, service entrance cable and main panel, (4) inspection and reconnection. Most jurisdictions also require the work to meet current code — which may trigger additional requirements like AFCI breakers on bedroom circuits or grounding improvements." },
      { type: "h2", text: "Load calculation first" },
      { type: "p", text: "Before upgrading, a licensed electrician should perform an NEC Article 220 load calculation to confirm that 200 amps is sufficient for your current and planned loads. Very large homes with multiple EV chargers, electric ranges, heat pumps and electric dryers can exceed 200 amps — in which case 320 or 400-amp service may be appropriate." },
    ],
  },
  {
    slug: "awg-wire-gauge-chart-explained",
    title: "AWG Wire Gauge Chart: What the Numbers Mean",
    description: "American Wire Gauge runs backward -- smaller AWG number means bigger wire. Here's a quick reference chart of common gauges with diameter, ampacity and uses.",
    keyword: "wire gauge chart",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "American Wire Gauge (AWG) is counterintuitive: a smaller number means a thicker, higher-capacity wire. Here's how to read the gauge scale and which gauge to use for common residential applications." },
      { type: "h2", text: "Why AWG runs backward" },
      { type: "p", text: "AWG traces back to the number of drawing dies a wire was pulled through to reach its final diameter. More draws = smaller wire. So 24 AWG (used in telephone wire) was drawn through 24 dies; 4/0 (zero-zero-zero — a very heavy cable) was barely drawn at all." },
      { type: "h2", text: "Quick reference chart (copper, 60°C column)" },
      { type: "ul", items: [
        "14 AWG — 15 amps — lighting circuits, general outlets (15A circuit)",
        "12 AWG — 20 amps — kitchen small-appliance circuits, bathroom outlets (20A circuit)",
        "10 AWG — 30 amps — dryers, water heaters, 30A circuits",
        "8 AWG — 40 amps — ranges, EV chargers on 40A circuits",
        "6 AWG — 55 amps — 50A circuits (EV chargers, large appliances)",
        "4 AWG — 70 amps — feeder circuits, sub-panels",
        "2 AWG — 95 amps — larger feeders",
        "1/0 AWG — 125 amps — service entrances for 100A service (sometimes)",
        "2/0 AWG — 145 amps — 150A service",
        "4/0 AWG — 195 amps — 200A service entrance",
      ] },
      { type: "h2", text: "Using 75°C terminals" },
      { type: "p", text: "The values above are for the 60°C column — the NEC default for circuits under 100A (NEC 110.14(C)(1)). If your terminals are rated 75°C (most modern panels are), you can use the 75°C ampacity column, which allows a smaller wire size in some cases. Always confirm terminal temperature rating before stepping down a wire size." },
    ],
  },
  {
    slug: "240v-outlet-wiring-guide",
    title: "240V Outlet Wiring: NEMA Types and Installation",
    description: "240V outlets come in NEMA 6-20, 6-30, 14-30 and 14-50 configurations. Here's which to use for which application and how a 240V circuit differs from 120V.",
    keyword: "240v outlet wiring",
    date: "2026-06-20",
    readMins: 5,
    body: [
      { type: "p", text: "A 240V outlet uses two hot legs from the panel — each 120V from neutral but 240V between them. This allows appliances to get double the voltage from the same panel and draw the same wattage at half the current. Here is how to pick the right NEMA configuration and install it correctly." },
      { type: "h2", text: "How 240V differs from 120V" },
      { type: "p", text: "A standard 120V circuit has one hot (black), one neutral (white) and a ground (green/bare). A 240V circuit has two hots (black and red), a neutral (white — not always required) and a ground. The circuit uses a double-pole breaker that simultaneously opens both hot legs on a fault." },
      { type: "h2", text: "NEMA 240V outlet types" },
      { type: "ul", items: [
        "NEMA 6-20: 20A, 240V, 2-pole, no neutral — for equipment like some compressors and welders.",
        "NEMA 6-30: 30A, 240V, 2-pole, no neutral — for some welders and large power tools.",
        "NEMA 14-30: 30A, 240V, 3-pole + ground — the standard dryer outlet (4-wire).",
        "NEMA 14-50: 50A, 240V, 3-pole + ground — the standard EV charger and RV outlet.",
      ] },
      { type: "h2", text: "When you need a neutral" },
      { type: "p", text: "240V appliances that have a 120V component (a clock, a motor control, an interior light) need a neutral for that 120V portion. Dryers, ranges and EV chargers with a control board all require a neutral. Pure 240V loads — resistance heaters, some water heaters — do not need a neutral and use 2-pole configurations (NEMA 6 series)." },
      { type: "h2", text: "Wire and breaker sizing" },
      { type: "p", text: "Use CircuitCalcHQ's wire size calculator to enter your load in amps and run length. For a 50-amp NEMA 14-50 (EV or RV): 6 AWG copper, 50-amp double-pole breaker. For a 30-amp NEMA 14-30 (dryer): 10 AWG copper, 30-amp double-pole breaker. Always verify with your local AHJ — some jurisdictions add requirements beyond the NEC minimum." },
    ],
  },
];

POSTS.push(...WEEK2_POSTS);
